// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsPR7_pOSl8lmGJyimp0VnOu4y1saFfF8',
    appId: '1:175497597531:web:35cc203a39c269674ee57e',
    messagingSenderId: '175497597531',
    projectId: 'crud-firebase---flutter',
    authDomain: 'crud-firebase---flutter.firebaseapp.com',
    storageBucket: 'crud-firebase---flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByS7j_CXc4Pms2qaJgAE31pfPsS6WeOzs',
    appId: '1:175497597531:android:60fdbce71a92cdce4ee57e',
    messagingSenderId: '175497597531',
    projectId: 'crud-firebase---flutter',
    storageBucket: 'crud-firebase---flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0532uzITkqV_RrfLdLiGwcPDZHzPTUyM',
    appId: '1:175497597531:ios:a6564d7d94ffad8a4ee57e',
    messagingSenderId: '175497597531',
    projectId: 'crud-firebase---flutter',
    storageBucket: 'crud-firebase---flutter.appspot.com',
    iosClientId: '175497597531-96e4cu6sq12v2ig81pnn445rq1f6naii.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanStateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0532uzITkqV_RrfLdLiGwcPDZHzPTUyM',
    appId: '1:175497597531:ios:a6564d7d94ffad8a4ee57e',
    messagingSenderId: '175497597531',
    projectId: 'crud-firebase---flutter',
    storageBucket: 'crud-firebase---flutter.appspot.com',
    iosClientId: '175497597531-96e4cu6sq12v2ig81pnn445rq1f6naii.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanStateManagement',
  );
}
